Repository awslabs/service-workbench-on-aws, pull requests merged in 2021-12, with the labels that each got.

#829 fix: cidr port range check
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-cidr-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-environment-sc-cidr.json
Labels: size/s

#833 Fix versioning artifacts
  main/cicd/cicd-pipeline/serverless.yml
  main/cicd/cicd-source/serverless.yml
  main/solution/backend/serverless.yml
  main/solution/edge-lambda/serverless.yml
  main/solution/infrastructure/serverless.yml
  main/solution/post-deployment/serverless.yml
  main/solution/pre-deployment/serverless.yml
  main/solution/ui/serverless.yml
Labels: size/s

#834 fix: add key rotation
  main/solution/backend/config/infra/cloudformation.yml
Labels: size/xs

#836 fix: add kms permission to work with cicd pipeline
  main/cicd/README.md
  main/cicd/cicd-pipeline/config/infra/cloudformation.yml
Labels: size/s

#843 fix: elb logging on
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/application-load-balancer.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/onboard-account.cfn.yml
  addons/addon-base-raas/packages/base-raas-services/lib/alb/__tests__/alb-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/alb/alb-service.js
  main/solution/backend/config/infra/functions.yml
  main/solution/infrastructure/config/infra/cloudformation.yml
Labels: size/m

#847 chore: changelog update
  CHANGELOG.md
Labels: size/s

#848 fix: dependency update
  docs/package.json
  docs/yarn.lock
Labels: size/s
