Repository awslabs/service-workbench-on-aws, pull requests merged in 2021-07, with the labels that each got.

#562 Fix: Zhaxan/gali 932 egress store toggle setting - fix update stack policy in postdeployment step
  addons/addon-stack-policy/packages/stack-policy/lib/steps/__test__/update-cfn-stack-policy.test.js
  addons/addon-stack-policy/packages/stack-policy/lib/steps/update-cfn-stack-policy.js
Labels: size/s

#563 story: token expiry
  addons/addon-base-ui/packages/base-ui/src/AppContainer.js
  addons/addon-base-ui/packages/base-ui/src/parts/ForceLogout.js
  addons/addon-base-ui/packages/base-ui/src/parts/__tests__/ForceLogout.test.js
  addons/addon-base-ui/packages/base-ui/src/plugins/app-component-plugin.js
Labels: size/m

#571 feat: Story update connect
  addons/addon-base-raas-appstream/README.md
  addons/addon-base-raas-appstream/packages/base-raas-appstream-rest-api/.eslintrc.json
  addons/addon-base-raas-appstream/packages/base-raas-appstream-rest-api/.gitignore
  addons/addon-base-raas-appstream/packages/base-raas-appstream-rest-api/.prettierrc.json
  addons/addon-base-raas-appstream/packages/base-raas-appstream-rest-api/jest.config.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-rest-api/jsconfig.json
  addons/addon-base-raas-appstream/packages/base-raas-appstream-rest-api/lib/plugins/services-plugin.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-rest-api/package.json
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/.eslintrc.json
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/.gitignore
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/.prettierrc.json
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/jest.config.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/jsconfig.json
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/appstream/appstream-sc-env-config-vars-service.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/appstream/appstream-sc-service.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/plugins/env-sc-connection-url-plugin.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/plugins/env-sc-provisioning-plugin.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/package.json
  addons/addon-base-raas-ui/packages/base-raas-ui/src/models/environments-sc/ScEnvConnectionStore.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvHttpConnectionExpanded.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentHttpConnections.js
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/onboard-account.cfn.yml
  main/solution/.pnpm-debug.log
  main/solution/backend/package.json
  main/solution/backend/src/lambdas/api-handler/plugins/plugin-registry.js
  pnpm-lock.yaml
Labels: size/xl

#573 fix: application version number
  main/config/settings/.defaults.yml
Labels: size/xs

#567 feat: [GALI-887] - Zhaxan/gali 887 egress object tagging
  addons/addon-base-raas-ui/packages/base-raas-ui/src/models/environments-sc/ScEnvironmentsStore.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentButtons.js
  addons/addon-base-raas/packages/base-raas-services/lib/compute/__test__/compute-platform-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/__test__/data-egress-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/data-egress-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-config-vars-service.js
  addons/addon-base/packages/services/lib/__test__/s3-service.test.js
  addons/addon-base/packages/services/lib/s3-service.js
  addons/addon-stack-policy/packages/stack-policy/lib/steps/update-cfn-stack-policy.js
  main/config/settings/.defaults.yml
  main/config/settings/example.yml
  main/solution/backend/config/infra/cloudformation.yml
  main/solution/backend/config/infra/functions.yml
  main/solution/backend/config/settings/.defaults.yml
  main/solution/backend/package.json
  main/solution/backend/serverless.yml
  main/solution/backend/src/lambdas/egress-store-object-handler/__tests__/handler.test.js
  main/solution/backend/src/lambdas/egress-store-object-handler/handler.js
  main/solution/backend/src/lambdas/egress-store-object-handler/plugins/plugin-registry.js
  pnpm-lock.yaml
Labels: size/l

#578 feat: Appstream connection updates
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/appstream/appstream-sc-service.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/plugins/env-sc-connection-url-plugin.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvHttpConnectionExpanded.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvSshConnRowExpanded.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentHttpConnections.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentRdpConnectionRow.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentSshConnectionRow.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentSshConnections.js
  main/solution/backend/src/lambdas/workflow-loop-runner/plugins/plugin-registry.js
  scripts/app-stream/SETUP.md
  scripts/app-stream/buildImage.ps1
  scripts/app-stream/ec2linux.ps1
Labels: size/l

#580 feat: appstream connect UI changes
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/appstream/appstream-sc-service.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/plugins/env-sc-connection-url-plugin.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/package.json
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentHttpConnections.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentRdpConnectionRow.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentRdpConnections.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentSshConnections.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-connection-service.js
Labels: size/m

#579 Fix: Deployment error in EgressStoreObjectHandler Lambda
  addons/addon-base-raas/packages/base-raas-services/lib/compute/__test__/compute-platform-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/compute/__test__/compute-price-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/__test__/data-egress-service.test.js
  main/solution/backend/config/infra/cloudformation.yml
  main/solution/backend/config/infra/functions.yml
  main/solution/backend/serverless.yml
  main/solution/post-deployment/config/infra/cloudformation.yml
  main/solution/post-deployment/config/infra/functions.yml
  main/solution/post-deployment/config/settings/.defaults.yml
  main/solution/post-deployment/package.json
  main/solution/post-deployment/serverless.yml
  main/solution/post-deployment/src/lambdas/egress-store-object-handler/__tests__/handler.test.js
  main/solution/post-deployment/src/lambdas/egress-store-object-handler/handler.js
  main/solution/post-deployment/src/lambdas/egress-store-object-handler/plugins/plugin-registry.js
  pnpm-lock.yaml
Labels: size/xl

#582 fix: serverless-plugin-ifelse dependency
  main/solution/backend/package.json
  main/solution/post-deployment/package.json
  pnpm-lock.yaml
Labels: size/xs

#583 feat: AppStream code hardening
  addons/addon-base-raas-appstream/packages/base-raas-appstream-rest-api/package.json
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/appstream/appstream-sc-service.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/appstream/tests/appstream-sc-service.test.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/plugins/__tests__/env-sc-connection-url-plugin.test.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/plugins/env-sc-connection-url-plugin.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/package.json
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentHttpConnections.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentRdpConnections.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentSshConnections.js
  main/end-to-end-tests/cypress/integration/workspaces.appstream.spec.js
  main/end-to-end-tests/package-lock.json
  main/end-to-end-tests/package.json
  pnpm-lock.yaml
Labels: size/xl

#593 docs: Added details found needed while onboarding
  docs/docs/deployment/deployment/index.md
  main/end-to-end-tests/README.md
Labels: size/s

#584 Feat: GALI-888 egress notification
  addons/addon-base-raas-ui/packages/base-raas-ui/src/helpers/api.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/helpers/settings.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/models/environments-sc/ScEnvironmentEgressStoreDetailStore.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/models/environments-sc/ScEnvironmentsStore.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentButtons.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentEgressStoreDetail.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/plugins/app-context-items-plugin.js
  addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/data-egress-controller.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/__test__/data-egress-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/data-egress-service.js
  addons/addon-base/packages/services/lib/__test__/s3-service.test.js
  addons/addon-base/packages/services/lib/s3-service.js
  main/config/settings/.defaults.yml
  main/solution/backend/config/infra/cloudformation.yml
  main/solution/backend/config/infra/functions.yml
  main/solution/backend/config/settings/.defaults.yml
  main/solution/post-deployment/config/infra/cloudformation.yml
  main/solution/post-deployment/config/infra/functions.yml
Labels: size/xl

#598 fix: s3 service to export api when init
  addons/addon-base/packages/services/lib/s3-service.js
Labels: size/xs

#594 feat: workspace provisioning mgmt
  addons/addon-base-raas-ui/packages/base-raas-ui/src/models/projects/Project.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/ScEnvironmentsList.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/setup/CreateInternalEnvForm.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/setup/ScEnvironmentSetup.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-cidr-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-connection-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/project/__tests__/project-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/project/project-service.js
  main/end-to-end-tests/cypress.local.example.json
  main/end-to-end-tests/cypress/integration/workspaces.appstream.spec.js
  main/end-to-end-tests/cypress/support/commands.js
Labels: size/l

#599 fix: await async methods
  addons/addon-base-raas/packages/base-raas-services/lib/project/project-service.js
Labels: size/xs

#600 fix: prevent redundant looping
  addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/environment-sc-controller.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-cidr-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-connection-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-service.js
Labels: size/s

#601 fix: unit test env connection & S3 service
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-connection-service.test.js
  addons/addon-base/packages/services/lib/s3-service.js
Labels: size/xs

#604 fix: using the string value of AppStream flag
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/project/project-service.js
Labels: size/xs

#612 feat: post deploy appstream step
  addons/addon-stack-policy/packages/stack-policy/lib/steps/__test__/__fixtures__/settings.js
  addons/addon-stack-policy/packages/stack-policy/lib/steps/__test__/update-cfn-stack-policy.test.js
  addons/addon-stack-policy/packages/stack-policy/lib/steps/update-cfn-stack-policy.js
  main/solution/backend/config/infra/cloudformation.yml
  main/solution/post-deployment/config/infra/functions.yml
Labels: size/l

#550 test: add provisioning env w/ studies and adv study perm int tests
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/lib/environment-type/__tests__/env-type-config-service.test.js
  main/integration-tests/__test__/advanced-tests/study-permissions/verify-linux-study-permissions.test.js
  main/integration-tests/__test__/api-tests/studies/get-studies.test.js
  main/integration-tests/__test__/api-tests/workspace-service-catalogs/create-workspace-service-catalog.test.js
  main/integration-tests/config/settings/example.yml
  main/integration-tests/package.json
  main/integration-tests/support/aws/services.js
  main/integration-tests/support/complex/run-shell-command.js
  main/integration-tests/support/resources/studies/study.js
  main/integration-tests/support/resources/workflows/workflow-version.js
  main/integration-tests/support/resources/workspace-service-catalogs/workspace-service-catalog.js
  main/integration-tests/support/setup.js
  pnpm-lock.yaml
Labels: size/xl
