Repository awslabs/service-workbench-on-aws, pull requests merged in 2021-03, with the labels that each got.

#351 chore: add schema checking to the DataSource APIs
  addons/addon-base-raas/packages/base-raas-services/lib/data-source/__tests__/data-source-account-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-source/__tests__/data-source-bucket-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-source/__tests__/data-source-reachability-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-source/data-source-reachability-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/schema/attempt-reach-data-source.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/register-data-source-account.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/register-data-source-bucket.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/register-study.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-data-source-account.json
  addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-service.test.js
  openapi.yaml
Labels: enhancement

#353 fix: sagemaker status pull
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-service.js
Labels: size/m

#357 docs: CHANGELOG update for release 2.0.2
  CHANGELOG.md
Labels: size/s

#352 chore: update input validation
  addons/addon-base-raas/packages/base-raas-services/lib/budgets/__tests__/budgets-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-connection-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/schema/create-budget.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/create-study.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/create-user.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/get-study-permissions.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/ssh-connection-info-sc.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-aws-accounts.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-environment-sc.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-indexes.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-project.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-study.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-user-roles.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-user.json
  addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-permission-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/study/study-permission-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/study/study-service.js
  addons/addon-base-workflow/packages/base-workflow-core/lib/schema/update-wf-assignment.json
  addons/addon-base/packages/services/lib/schema/create-user.json
  addons/addon-base/packages/services/lib/schema/update-user.json
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/lib/environment-type/__tests__/env-type-config-service.test.js
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/lib/environment-type/__tests__/env-type-service.test.js
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/lib/environment-type/schema/create-env-type.js
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/lib/environment-type/schema/create-or-update-env-type-config.js
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/lib/environment-type/schema/update-env-type.js
  openapi.yaml
Labels: enhancement, size/l

#363 chore: add clarity to tests and make schema more permissible
  addons/addon-base-raas/packages/base-raas-services/lib/budgets/__tests__/budgets-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-source/__tests__/data-source-account-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-source/__tests__/data-source-bucket-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-source/__tests__/data-source-reachability-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-connection-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/schema/attempt-reach-data-source.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/create-budget.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/create-study.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/get-study-permissions.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/register-data-source-account.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/register-data-source-bucket.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/register-study.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/ssh-connection-info-sc.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-data-source-account.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-study.json
  addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-permission-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-service.test.js
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/lib/environment-type/__tests__/env-type-config-service.test.js
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/lib/environment-type/__tests__/env-type-service.test.js
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/lib/environment-type/schema/create-env-type.js
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/lib/environment-type/schema/create-or-update-env-type-config.js
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/lib/environment-type/schema/update-env-type.js
Labels: enhancement, size/m

#377 test: Add integ Tests for Budget API
  addons/addon-base-raas-ui/packages/base-raas-ui/src/helpers/api.js
  addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/budgets-controller.js
  main/integration-tests/__test__/api-tests/budgets/create-budget.test.js
  main/integration-tests/__test__/api-tests/budgets/get-budget.test.js
  main/integration-tests/__test__/api-tests/budgets/update-budget.test.js
  main/integration-tests/config/settings/example.yml
  main/integration-tests/support/resources.js
  main/integration-tests/support/resources/budgets/budget.js
  main/integration-tests/support/resources/budgets/budgets.js
  main/integration-tests/support/utils/generators.js
  openapi.yaml
Labels: size/m

#382 docs: Integ test documentation
  main/integration-tests/README.md
  openapi.yaml
Labels: size/s

#391 docs: update CHANGELOG
  CHANGELOG.md
Labels: size/xs

#393 refactor: restrict data source reachability Lambda role
  main/solution/backend/config/infra/cloudformation.yml
  main/solution/backend/config/infra/functions.yml
  main/solution/backend/serverless.yml
Labels: size/m

#401 docs: Update CHANGELOG for 2.1.1 release
  CHANGELOG.md
Labels: size/s

#404 chore: update docs dependencies
  docs/package.json
  docs/yarn.lock
Labels: size/m

#405 chore: update more docs dependencies
  docs/package.json
  docs/yarn.lock
Labels: size/xl

#407 ci: fix gh merge workflow to do ff-only
  .github/workflows/deploy-integ.yml
Labels: size/s
