Repository awslabs/service-workbench-on-aws, pull requests merged in 2021-06, with the labels that each got.

#510 feat: [feat-secure-workspace-egress] GALI-884 Backend Egress Store Initiation
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/ec2-linux-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/ec2-rstudio-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/external/sagemaker.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/sagemaker-notebook-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-linux-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-rstudio-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-windows-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/emr-cluster.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/sagemaker-notebook-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/__test__/data-egress-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/data-egress-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-source/access-strategy/legacy/environment-resource-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-source/access-strategy/roles-only/environment-resource-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-config-vars-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-config-vars-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/helpers/__tests__/utils.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/helpers/utils.js
  addons/addon-base-raas/packages/base-raas-services/lib/plugins/roles-only-strategy-plugin.js
  addons/addon-base-raas/packages/base-raas-services/lib/schema/create-egress-store.json
  addons/addon-base-workflow/packages/base-workflow-core/lib/runner/plugins/services-plugin.js
  addons/addon-base/packages/services/lib/s3-service.js
  main/solution/backend/config/infra/cloudformation.yml
  main/solution/backend/config/infra/functions.yml
  main/solution/backend/config/settings/.defaults.yml
  pnpm-lock.yaml
Labels: size/xl

#516 feat: [feat-secure-workspace-egress] GALI-933 and GALI-934 add UI changes for egress store request submission
  addons/addon-base-raas-ui/packages/base-raas-ui/src/helpers/api.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/helpers/settings.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/models/environments-sc/ScEnvironmentEgressStoreDetailStore.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentButtons.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentEgressStoreDetail.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/plugins/app-context-items-plugin.js
  addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/data-egress-controller.js
  addons/addon-base-raas/packages/base-raas-rest-api/lib/plugins/routes-plugin.js
  addons/addon-base-raas/packages/base-raas-rest-api/lib/plugins/services-plugin.js
Labels: size/m

#540 chore: upgrade dependencies
  docs/package.json
  docs/yarn.lock
Labels: size/m

#542 chore: specify Node.js and Go versions across docs
  README.md
  addons/addon-base-raas/packages/serverless-packer/README.md
  addons/addon-base-ui/packages/serverless-ui-tools/README.md
  addons/addon-base/packages/serverless-go-build-tools/README.md
  docs/docs/deployment/pre_deployment/prereq_commands.md
Labels: size/s

#548 chore: update changelog
  CHANGELOG.md
Labels: size/xs
