Repository awslabs/service-workbench-on-aws, pull requests merged in 2021-02, with the labels that each got.

#289 fix: labeler .yml syntax
  .github/workflows/labeler.yml
Labels: size/xs

#293 docs: Update CHANGELOG
  CHANGELOG.md
Labels: size/s

#290 feat: Integration Test setup
  main/cicd/cicd-pipeline/config/buildspec/buildspec-int-tests.yml
  main/cicd/cicd-pipeline/config/buildspec/buildspec.yml
  main/cicd/cicd-pipeline/scripts/upload-test-config-if-not-versioned.sh
  main/cicd/cicd-pipeline/serverless.yml
  main/integration-tests/README.md
  main/integration-tests/__test__/api-tests/public-auth-provider-api.test.js
  main/integration-tests/__test__/api-tests/studies/__fixtures__/update-study-fixture.js
  main/integration-tests/__test__/api-tests/studies/update-study-api.test.js
  main/integration-tests/config/settings/example.yml
  main/integration-tests/helpers/api-param-generator.js
  main/integration-tests/helpers/base-fixture.js
  main/integration-tests/package.json
  main/integration-tests/utils/auth-tokens.js
  main/integration-tests/utils/common.js
  main/integration-tests/utils/studies.js
  main/integration-tests/utils/users.js
  main/solution/backend/src/lambdas/env-status-poll-handler/plugins/plugin-registry.js
  pnpm-lock.yaml
  scripts/run-integration-tests.sh
  scripts/util.sh
Labels: enhancement, size/l

#317 chore: enforce running integ tests prior to merges into `mainline`
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy-integ.yml
  .github/workflows/labeler.yml
  .github/workflows/mainline-protection.yaml
  .github/workflows/test.yml
  .github/workflows/unit-test-code-analysis.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  addons/addon-base-post-deployment/packages/base-post-deployment/.gitignore
  addons/addon-base-raas-ui/packages/base-raas-ui/.gitignore
  addons/addon-base-raas/packages/base-raas-cfn-templates/.gitignore
  addons/addon-base-raas/packages/base-raas-post-deployment/.gitignore
  addons/addon-base-raas/packages/base-raas-rest-api/.gitignore
  addons/addon-base-raas/packages/base-raas-services/.gitignore
  addons/addon-base-raas/packages/base-raas-workflow-steps/.gitignore
  addons/addon-base-raas/packages/base-raas-workflows/.gitignore
  addons/addon-base-raas/packages/serverless-packer/.gitignore
  addons/addon-base-rest-api/packages/api-handler-factory/.gitignore
  addons/addon-base-rest-api/packages/base-api-handler/.gitignore
  addons/addon-base-rest-api/packages/base-authn-handler/.gitignore
  addons/addon-base-rest-api/packages/base-controllers/.gitignore
  addons/addon-base-rest-api/packages/services/.gitignore
  addons/addon-base-ui/packages/base-ui/.gitignore
  addons/addon-base-ui/packages/serverless-ui-tools/.gitignore
  addons/addon-base-workflow-api/packages/base-worklfow-api/.gitignore
  addons/addon-base-workflow-ui/packages/base-workflow-ui/.gitignore
  addons/addon-base-workflow/packages/base-workflow-core/.gitignore
  addons/addon-base-workflow/packages/base-workflow-templates/.gitignore
  addons/addon-base-workflow/packages/base-worklfow-steps/.gitignore
  addons/addon-base-workflow/packages/workflow-engine/.gitignore
  addons/addon-base/packages/serverless-backend-tools/.gitignore
  addons/addon-base/packages/serverless-go-build-tools/.gitignore
  addons/addon-base/packages/services-container/.gitignore
  addons/addon-base/packages/services/.gitignore
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/.gitignore
  addons/addon-environment-sc-api/packages/environment-sc-workflows/.gitignore
  addons/addon-environment-sc-api/packages/environment-type-mgmt-api/.gitignore
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/.gitignore
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/.gitignore
  addons/addon-key-pair-mgmt-api/packages/key-pair-mgmt-api/.gitignore
  addons/addon-key-pair-mgmt-api/packages/key-pair-mgmt-services/.gitignore
  addons/addon-key-pair-mgmt-ui/packages/key-pair-mgmt-ui/.gitignore
  addons/addon-raas-s3-copy/packages/s3-synchronizer/.gitignore
  addons/addon-user-id-upgrade/packages/user-id-upgrade-post-deployment/.gitignore
  main/cicd/.gitignore
  main/integration-tests/.gitignore
  main/packages/.gitignore
  main/packages/controllers/.gitignore
  main/packages/services/.gitignore
  main/solution/.gitignore
  main/solution/backend/.gitignore
  main/solution/edge-lambda/.gitignore
  main/solution/environment-tools/.gitignore
  main/solution/infrastructure/.gitignore
  main/solution/machine-images/.gitignore
  main/solution/post-deployment/.gitignore
  main/solution/prepare-master-acc/.gitignore
  main/solution/ui/.gitignore
  scripts/load-test-workspaces/.gitignore
Labels: enhancement, size/m

#341 docs: Update which branch to work off of
  CONTRIBUTING.md
Labels: documentation, size/xs

#337 Test: Add test for users APIs
  addons/addon-base/packages/services/lib/authorization/authorization-utils.js
  addons/addon-base/packages/services/lib/user/__tests__/user-authz-service.test.js
  addons/addon-base/packages/services/lib/user/user-authz-service.js
  main/integration-tests/__test__/api-tests/users/bulk-add-users.test.js
  main/integration-tests/__test__/api-tests/users/create-user.test.js
  main/integration-tests/__test__/api-tests/users/delete-user.test.js
  main/integration-tests/__test__/api-tests/users/get-users.test.js
  main/integration-tests/__test__/api-tests/users/update-user-password.test.js
  main/integration-tests/__test__/api-tests/users/update-user.test.js
  main/integration-tests/__test__/api-tests/workspace-types/configurations/delete-configuration.test.js
  main/integration-tests/__test__/api-tests/workspace-types/delete-workspace-type.test.js
  main/integration-tests/support/resources/base/resource.js
  main/integration-tests/support/resources/users/user.js
  main/integration-tests/support/resources/users/users.js
Labels: size/l

#349 fix: lodash dependency upgrade
  addons/addon-base-post-deployment/packages/base-post-deployment/package.json
  addons/addon-base-raas-ui/packages/base-raas-ui/package.json
  addons/addon-base-raas/packages/base-raas-post-deployment/package.json
  addons/addon-base-raas/packages/base-raas-rest-api/package.json
  addons/addon-base-raas/packages/base-raas-services/package.json
  addons/addon-base-raas/packages/base-raas-workflow-steps/package.json
  addons/addon-base-raas/packages/base-raas-workflows/package.json
  addons/addon-base-raas/packages/serverless-packer/package.json
  addons/addon-base-rest-api/packages/api-handler-factory/package.json
  addons/addon-base-rest-api/packages/base-api-handler/package.json
  addons/addon-base-rest-api/packages/base-authn-handler/package.json
  addons/addon-base-rest-api/packages/base-controllers/package.json
  addons/addon-base-rest-api/packages/services/package.json
  addons/addon-base-ui/packages/base-ui/package.json
  addons/addon-base-ui/packages/serverless-ui-tools/package.json
  addons/addon-base-workflow-api/packages/base-worklfow-api/package.json
  addons/addon-base-workflow-ui/packages/base-workflow-ui/package.json
  addons/addon-base-workflow/packages/base-workflow-core/package.json
  addons/addon-base-workflow/packages/base-workflow-templates/package.json
  addons/addon-base-workflow/packages/base-worklfow-steps/package.json
  addons/addon-base-workflow/packages/workflow-engine/package.json
  addons/addon-base/packages/serverless-backend-tools/package.json
  addons/addon-base/packages/serverless-go-build-tools/package.json
  addons/addon-base/packages/services-container/package.json
  addons/addon-base/packages/services/package.json
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/package.json
  addons/addon-environment-sc-api/packages/environment-sc-workflows/package.json
  addons/addon-environment-sc-api/packages/environment-type-mgmt-api/package.json
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/package.json
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/package.json
  addons/addon-key-pair-mgmt-api/packages/key-pair-mgmt-api/package.json
  addons/addon-key-pair-mgmt-api/packages/key-pair-mgmt-services/package.json
  addons/addon-key-pair-mgmt-ui/packages/key-pair-mgmt-ui/package.json
  addons/addon-user-id-upgrade/packages/user-id-upgrade-post-deployment/package.json
  main/integration-tests/package.json
  main/packages/controllers/package.json
  main/packages/services/package.json
  main/solution/backend/package.json
  main/solution/post-deployment/package.json
  main/solution/ui/package.json
  pnpm-lock.yaml
Labels: dependencies, size/l
