Repository awslabs/service-workbench-on-aws, pull requests merged in 2021-09, with the labels that each got.

#690 fix: revert the changes to prepopulate configuration variables
  addons/addon-base-ui/packages/base-ui/src/parts/helpers/fields/DropDown.js
  addons/addon-base-ui/packages/base-ui/src/parts/helpers/fields/__tests__/DropDown.test.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/EnvTypeCard.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/EnvTypeEditor.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-config/env-type-config-steps/AccessControlStep.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-config/env-type-config-steps/BaseEnvTypeConfigStep.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-config/env-type-config-steps/BasicInfoStep.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-config/env-type-config-steps/InputParamsStep.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-editor-steps/ConfigStep.js
  main/end-to-end-tests/README.md
  main/end-to-end-tests/cypress.github.json
  main/end-to-end-tests/cypress.json
  main/end-to-end-tests/cypress/integration/workspaces.spec.js
  main/end-to-end-tests/cypress/integration/workspacetypes.spec.js
Labels: size/m

#693 fix: save the config variables when they are pre-populated
  addons/addon-base-ui/packages/base-ui/src/parts/helpers/fields/DropDown.js
  addons/addon-base-ui/packages/base-ui/src/parts/helpers/fields/__tests__/DropDown.test.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/EnvTypeCard.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-config/env-type-config-steps/AccessControlStep.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-config/env-type-config-steps/BaseEnvTypeConfigStep.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-config/env-type-config-steps/BasicInfoStep.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-config/env-type-config-steps/InputParamsStep.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-editor-steps/ConfigStep.js
  main/end-to-end-tests/README.md
  main/end-to-end-tests/cypress.github.json
  main/end-to-end-tests/cypress.json
  main/end-to-end-tests/cypress/integration/workspace-types.spec.js
  main/end-to-end-tests/cypress/integration/workspaces.spec.js
Labels: size/m

#697 chore: normalize all the line endings
  .github/workflows/mainline-protection.yaml
  addons/addon-base-raas/packages/base-raas-services/lib/schema/attempt-reach-data-source.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/get-study-permissions.json
Labels: size/m

#702 chore: update goofys to 0.24.0
  main/solution/post-deployment/config/environment-files/bootstrap.sh
Labels: size/xs

#703 fix: no sagemaker autostop lag
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-service.js
  addons/addon-base/packages/services/lib/__mocks__/db-service.js
  main/solution/backend/src/lambdas/env-status-poll-handler/handler.js
Labels: size/m

#705 fix: properly handle very long error messages on env update
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-service.js
Labels: size/s

#709 fix: sync UI and API func
  addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/project-controller.js
  addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/users-controller.js
  openapi.yaml
Labels: size/s

#711 fix: integ tests
  main/integration-tests/__test__/api-tests/projects/delete-project.test.js
  main/integration-tests/__test__/api-tests/users/delete-user.test.js
  main/integration-tests/support/complex/delete-project.js
  main/integration-tests/support/resources/projects/project.js
Labels: size/m

#712 fix: account onboarding error
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/aws-accounts-service.js
Labels: size/s

#713 fix: externalId requirement for add account form
  addons/addon-base-raas-ui/packages/base-raas-ui/src/models/forms/AddUpdateAwsAccountForm.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/accounts/__tests__/AddUpdateAwsAccount.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/__tests__/aws-accounts-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/aws-cfn-service.js
Labels: size/s

#717 fix: namespace code works with configs with no namespace param
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/__test__/launch-product.test.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/launch-product/launch-product.js
Labels: size/s

#720 feat: remove egress bucket pol
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/__test__/data-egress-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/data-egress-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-config-vars-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-config-vars-service.js
  main/solution/backend/config/infra/cloudformation.yml
Labels: size/m

#716 feat: dynamic version number from Changelog
  .github/workflows/deploy-integ.yml
  main/config/settings/.defaults.yml
  scripts/check-and-add-beta.sh
  scripts/environment-deploy.sh
Labels: size/m

#724 fix: put the version number and date code above the backend deployment code
  scripts/check-and-add-beta.sh
  scripts/environment-deploy.sh
Labels: size/m

#725 fix: bypass develop protection when adding beta
  .github/workflows/deploy-integ.yml
Labels: size/s

#722 test: restore advanced integ tests
  main/integration-tests/__test__/advanced-tests/study-permissions/verify-linux-study-permissions.test.js
  main/integration-tests/__test__/api-tests/workspace-service-catalogs/create-workspace-service-catalog.test.js
  main/integration-tests/config/settings/example.yml
  main/integration-tests/package.json
  main/integration-tests/support/complex/run-shell-command.js
  main/integration-tests/support/setup.js
  pnpm-lock.yaml
Labels: size/xl

#727 fix: flakiness integ setup
  main/integration-tests/support/setup.js
Labels: size/s
