Repository awslabs/service-workbench-on-aws, pull requests merged in 2021-04, with the labels that each got.

#412 refactor: restrict sc roles
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/onboard-account.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-linux-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-rstudio-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-windows-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/emr-cluster.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/sagemaker-notebook-instance.cfn.yml
  main/solution/backend/config/infra/cloudformation.yml
  main/solution/post-deployment/config/infra/cloudformation.yml
Labels: size/l

#433 refactor: Remove permission boundary condition on launch constraint role
  docs/docs/deployment/post_deployment/import_service_catalog_products.md
  main/solution/post-deployment/config/infra/cloudformation.yml
Labels: size/s

#442 fix: Open data handler fix
  addons/addon-base-raas/packages/base-raas-services/lib/schema/create-study.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-study.json
  addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-service.test.js
  main/solution/backend/config/infra/cloudformation.yml
  main/solution/backend/config/infra/functions.yml
  main/solution/backend/src/lambdas/open-data-scrape-handler/__tests__/handler-impl.test.js
  main/solution/backend/src/lambdas/open-data-scrape-handler/handler-impl.js
Labels: size/m

#460 chore: disable gcov & codecov fine tune
  .github/workflows/merge-coverage-report.yml
  .github/workflows/unit-test-code-analysis.yml
  addons/addon-base-post-deployment/packages/base-post-deployment/package.json
  addons/addon-base-raas-ui/packages/base-raas-ui/package.json
  addons/addon-base-raas/packages/base-raas-cfn-templates/package.json
  addons/addon-base-raas/packages/base-raas-post-deployment/package.json
  addons/addon-base-raas/packages/base-raas-rest-api/package.json
  addons/addon-base-raas/packages/base-raas-services/package.json
  addons/addon-base-raas/packages/base-raas-workflow-steps/package.json
  addons/addon-base-raas/packages/base-raas-workflows/package.json
  addons/addon-base-raas/packages/serverless-packer/package.json
  addons/addon-base-rest-api/packages/api-handler-factory/package.json
  addons/addon-base-rest-api/packages/base-api-handler/package.json
  addons/addon-base-rest-api/packages/base-authn-handler/package.json
  addons/addon-base-rest-api/packages/base-controllers/package.json
  addons/addon-base-rest-api/packages/services/package.json
  addons/addon-base-ui/packages/base-ui/package.json
  addons/addon-base-ui/packages/serverless-ui-tools/package.json
  addons/addon-base-workflow-api/packages/base-worklfow-api/package.json
  addons/addon-base-workflow/packages/base-workflow-core/package.json
  addons/addon-base-workflow/packages/base-workflow-templates/package.json
  addons/addon-base-workflow/packages/base-worklfow-steps/package.json
  addons/addon-base-workflow/packages/workflow-engine/package.json
  addons/addon-base/packages/serverless-backend-tools/package.json
  addons/addon-base/packages/serverless-go-build-tools/package.json
  addons/addon-base/packages/serverless-settings-helper/package.json
  addons/addon-base/packages/services-container/package.json
  addons/addon-base/packages/services/package.json
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/package.json
  addons/addon-environment-sc-api/packages/environment-sc-workflows/package.json
  addons/addon-environment-sc-api/packages/environment-type-mgmt-api/package.json
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/package.json
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/package.json
  addons/addon-key-pair-mgmt-api/packages/key-pair-mgmt-api/package.json
  addons/addon-key-pair-mgmt-api/packages/key-pair-mgmt-services/package.json
  addons/addon-user-id-upgrade/packages/user-id-upgrade-post-deployment/package.json
  codecov.yml
  main/packages/controllers/package.json
  main/packages/services/package.json
  main/solution/backend/package.json
  main/solution/post-deployment/package.json
Labels: size/s

#468 fix: properly handle SC products with no active versions
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/lib/environment-type/env-type-candidate-service.js
Labels: size/xs
