Repository awslabs/service-workbench-on-aws, pull requests merged in 2021-05, with the labels that each got.

#474 chore: crypto updates
  addons/addon-base-raas/packages/base-raas-services/lib/environment/built-in/environment-url-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-connection-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-connection-service.js
  addons/addon-base-raas/packages/base-raas-services/package.json
  addons/addon-base/packages/services/lib/helpers/rstudio-encryptor.js
  docs/docs/user_guide/sidebar/common/workspaces/accessing_a_workspace.md
  main/solution/machine-images/README.md
  pnpm-lock.yaml
Labels: size/l

#478 chore: depdendency updates
  scripts/load-test-workspaces/package-lock.json
Labels: size/s

#486 chore: privilege management appDeployer
  main/cicd/cicd-pipeline/config/infra/cloudformation.yml
Labels: size/s

#488 chore: dependabot suggested package versions
  docs/package.json
  docs/yarn.lock
Labels: size/s

#493 chore: Update UI to say 3.1
  main/config/settings/.defaults.yml
Labels: documentation, size/xs

#487 chore: Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/miscellaneous.md
Labels: size/s

#494 chore: update PR checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/xs

#502 fix: add termination status for non-found workspaces
  CHANGELOG.md
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-service.js
Labels: bug, size/m

#505 chore: docs dependency fix
  docs/package.json
  docs/yarn.lock
Labels: size/s
