Repository awslabs/service-workbench-on-aws, pull requests merged in 2021-11, with the labels that each got.

#789 fix: prevent duplicate hosted zone creation
  main/solution/infrastructure/config/infra/cloudformation.yml
Labels: size/s

#791 fix: update GH action to use custom domain
  .github/workflows/deploy-integ.yml
  scripts/read-values-for-github-action.sh
Labels: size/s

#793 fix: script permissions
  scripts/read-values-for-github-action.sh
Labels: size/xs

#794 fix: default hosted zone in infra
  main/solution/infrastructure/config/infra/cloudformation.yml
Labels: size/s

#790 fix: hsts header
  addons/addon-base-rest-api/packages/api-handler-factory/lib/handler.js
Labels: size/s

#795 chore: update CODEOWNERS
  CODEOWNERS
Labels: size/xs

#796 fix: replace get with post rstudio connect
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentHttpConnections.js
  main/solution/machine-images/config/infra/files/rstudio/nginx.conf
Labels: size/s

#779 fix: sc portfolio deletion correction
  scripts/environment-delete.sh
Labels: size/s

#800 chore: use custom domain for TRE e2etest env
  .github/workflows/deploy-integ-appstream-egress.yml
Labels: size/xs

#783 feat: integrating appstream with rstudio-alb
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/application-load-balancer.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/onboard-account.cfn.yml
  addons/addon-base-raas/packages/base-raas-services/lib/alb/__tests__/alb-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/alb/alb-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/__tests__/aws-cfn-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/aws-cfn-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/__tests__/environment-dns-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/environment-dns-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/plugins/__tests__/env-provisioning-plugin.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/plugins/env-provisioning-plugin.js
  addons/addon-base-raas/packages/base-raas-services/lib/schema/create-aws-accounts.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-aws-accounts.json
  addons/addon-base-raas/packages/base-raas-workflow-steps/lib/steps/__test__/provision-account.test.js
  addons/addon-base-raas/packages/base-raas-workflow-steps/lib/steps/provision-account/provision-account.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/__test__/check-launch-dependency.test.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/__test__/terminate-launch-dependency.test.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/check-launch-dependency/check-launch-dependency.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/launch-product/launch-product.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/terminate-launch-dependency/terminate-launch-dependency.js
Labels: size/xl

#802 fix: run TRE tests for develop merge
  .github/workflows/deploy-integ-appstream-egress.yml
Labels: size/xs

#805 chore: deprecate legacy rstudio
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/ScEnvironmentCard.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentHttpConnections.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentUpdateCidrs.js
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-rstudio-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-post-deployment/lib/steps/create-service-catalog-portfolio.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-connection-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-connection-service.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/check-launch-dependency/check-launch-dependency.js
  main/solution/machine-images/README.md
  main/solution/machine-images/config/infra/files/rstudio/check-idle
  main/solution/machine-images/config/infra/files/rstudio/nginx.conf
  main/solution/machine-images/config/infra/files/rstudio/set-password
  main/solution/machine-images/config/infra/packer-ec2-rstudio-workspace.json
  main/solution/machine-images/config/infra/provisioners/provision-rstudio.sh
Labels: size/l

#810 fix: set condition for public route table
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/onboard-account.cfn.yml
Labels: size/xs

#816 chore: end to end tests rstudio feature
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentHttpConnections.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/EnvTypeCandidatesList.js
  main/end-to-end-tests/README.md
  main/end-to-end-tests/cypress.appstream-egress.json
  main/end-to-end-tests/cypress.github.appstream-egress.json
  main/end-to-end-tests/cypress.github.json
  main/end-to-end-tests/cypress.json
  main/end-to-end-tests/cypress/integration/appstream-egress-disabled/workspaces.spec.js
  main/end-to-end-tests/cypress/integration/appstream-egress-enabled/workspaces.spec.js
  main/end-to-end-tests/cypress/integration/common/workspace-types.spec.js
  main/end-to-end-tests/cypress/support/workspace-util.js
Labels: size/m

#817 fix: remove custom domain condition infra cfn
  main/solution/infrastructure/config/infra/cloudformation.yml
Labels: size/xs

#819 chore: update changelog
  CHANGELOG.md
Labels: size/s

#820 fix: terminate workspaces after e2e tests in non tre environment
  main/end-to-end-tests/cypress/integration/appstream-egress-disabled/workspaces.spec.js
  main/end-to-end-tests/cypress/support/workspace-util.js
Labels: size/s

#821 fix: allow RStudio EC2 to initialize
  main/integration-tests/__test__/api-tests/common/advanced-tests/rstudio/launch-rstudio-workspace.test.js
Labels: size/xs

#822 fix: delete verify linux tests from common folder
  main/integration-tests/__test__/api-tests/common/advanced-tests/study-permissions/verify-linux-study-permissions.test.js
Labels: size/m

#823 chore: integration test cleanup for dummy envs
  main/integration-tests/__test__/api-tests/common/workspace-service-catalogs/cidr-workspace-service-catalog.test.js
  main/integration-tests/__test__/api-tests/common/workspace-service-catalogs/connections/create-url-connection.test.js
  main/integration-tests/__test__/api-tests/common/workspace-service-catalogs/connections/get-connections.test.js
  main/integration-tests/__test__/api-tests/common/workspace-service-catalogs/connections/send-ssh-public-key-connection.test.js
  main/integration-tests/__test__/api-tests/common/workspace-service-catalogs/connections/windows-rdp-info-connection.test.js
  main/integration-tests/__test__/api-tests/common/workspace-service-catalogs/create-workspace-service-catalog.test.js
  main/integration-tests/__test__/api-tests/common/workspace-service-catalogs/delete-workspace-service-catalog.test.js
  main/integration-tests/__test__/api-tests/common/workspace-service-catalogs/get-workspace-service-catalog.test.js
  main/integration-tests/__test__/api-tests/common/workspace-service-catalogs/get-workspace-service-catalogs.test.js
  main/integration-tests/__test__/api-tests/common/workspace-service-catalogs/start-workspace-service-catalog.test.js
  main/integration-tests/__test__/api-tests/common/workspace-service-catalogs/stop-workspace-service-catalog.test.js
  main/integration-tests/support/complex/delete-workspace-service-catalog.js
Labels: size/m
