Repository awslabs/service-workbench-on-aws, pull requests merged in 2021-08, with the labels that each got.

#619 fix: emr config
  main/integration-tests/config/settings/example.yml
Labels: size/xs

#615 fix: static namespace bug fix
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/__test__/launch-product.test.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/launch-product/launch-product.js
Labels: size/m

#602 feat: GALI-886-BYOB setting
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/data-sources/register/InputStep.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentButtons.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentEgressStoreDetail.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/__test__/data-egress-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/data-egress-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/schema/create-egress-store.json
  addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/study/study-service.js
  addons/addon-base-ui/packages/base-ui/src/parts/helpers/fields/YesNo.js
Labels: size/m

#607 fix: ui and backend egress logic while terminating workspace
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentButtons.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/data-egress-service.js
Labels: size/s

#621 chore: debug adv tests
  main/integration-tests/__test__/advanced-tests/study-permissions/verify-linux-study-permissions.test.js
  main/solution/ui/config/settings/.defaults.yml
Labels: size/m

#622 fix: delete empty test file
  main/integration-tests/__test__/advanced-tests/study-permissions/verify-linux-study-permissions.test.js
Labels: size/m

#629 fix: Static namespace fix linted
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/__test__/launch-product.test.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/launch-product/launch-product.js
Labels: size/m

#631 fix: remove workspace test that polls workflow
  main/integration-tests/__test__/api-tests/workspace-service-catalogs/create-workspace-service-catalog.test.js
Labels: size/s

#633 fix: get appstream setting optional bool
  addons/addon-base-raas/packages/base-raas-services/lib/account/__tests__/account-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/account/account-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/aws-accounts-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/aws-cfn-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/project/project-service.js
  addons/addon-base-raas/packages/base-raas-workflow-steps/lib/steps/__test__/provision-account.test.js
  addons/addon-base-raas/packages/base-raas-workflow-steps/lib/steps/provision-account/provision-account.js
  addons/addon-base/packages/services/lib/s3-service.js
  addons/addon-stack-policy/packages/stack-policy/lib/steps/__test__/update-cfn-stack-policy.test.js
  addons/addon-stack-policy/packages/stack-policy/lib/steps/update-cfn-stack-policy.js
Labels: size/s

#634 fix: update int test readme to include adv test info
  main/integration-tests/README.md
Labels: size/s

#638 fix: add method to get new token for adv tests
  main/integration-tests/__test__/advanced-tests/study-permissions/verify-linux-study-permissions.test.js
  main/integration-tests/__test__/api-tests/workflows/get-workflow-instances.test.js
  main/integration-tests/__test__/api-tests/workspace-service-catalogs/create-workspace-service-catalog.test.js
  main/integration-tests/config/settings/example.yml
Labels: size/m

#639 fix: egress store data access cross account
  addons/addon-base-raas/packages/base-raas-services/lib/data-source/__tests__/environment-resource-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-source/access-strategy/legacy/environment-resource-service.js
  main/solution/backend/config/infra/functions.yml
  main/solution/backend/config/settings/.defaults.yml
Labels: size/m

#643 fix: update kms policy when no study selected
  addons/addon-base-raas/packages/base-raas-services/lib/data-source/access-strategy/legacy/environment-resource-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-source/access-strategy/roles-only/__tests__/environment-resource-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-source/access-strategy/roles-only/environment-resource-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/plugins/__tests__/env-provisioning-plugin.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/plugins/env-provisioning-plugin.js
  addons/addon-base-raas/packages/base-raas-services/lib/plugins/roles-only-strategy-plugin.js
Labels: size/m

#646 fix: egress store should be terminated if it's not used after creation
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/__test__/data-egress-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/data-egress-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/helpers/utils.js
Labels: size/m

#640 fix: reset ForceLogout component upon relogin
  addons/addon-base-ui/packages/base-ui/src/parts/ForceLogout.js
  addons/addon-base-ui/packages/base-ui/src/parts/__tests__/ForceLogout.test.js
Labels: size/s

#648 fix: remove adv integ tests
  main/integration-tests/__test__/advanced-tests/study-permissions/verify-linux-study-permissions.test.js
  main/integration-tests/__test__/api-tests/workflows/get-workflow-instances.test.js
  main/integration-tests/__test__/api-tests/workspace-service-catalogs/create-workspace-service-catalog.test.js
Labels: size/m

#641 fix: go bug during deployment is handled
  addons/addon-base/packages/serverless-go-build-tools/index.js
Labels: size/s

#651 Egress/pre deployment validation
  addons/addon-base-pre-deployment/packages/base-pre-deployment/.eslintrc.json
  addons/addon-base-pre-deployment/packages/base-pre-deployment/.gitignore
  addons/addon-base-pre-deployment/packages/base-pre-deployment/.prettierrc.json
  addons/addon-base-pre-deployment/packages/base-pre-deployment/README.md
  addons/addon-base-pre-deployment/packages/base-pre-deployment/jest.config.js
  addons/addon-base-pre-deployment/packages/base-pre-deployment/jsconfig.json
  addons/addon-base-pre-deployment/packages/base-pre-deployment/lib/deployment-store-service.js
  addons/addon-base-pre-deployment/packages/base-pre-deployment/lib/plugins/services-plugin.js
  addons/addon-base-pre-deployment/packages/base-pre-deployment/lib/plugins/steps-plugin.js
  addons/addon-base-pre-deployment/packages/base-pre-deployment/lib/schema/deployment-item.json
  addons/addon-base-pre-deployment/packages/base-pre-deployment/lib/steps-registration-util.js
  addons/addon-base-pre-deployment/packages/base-pre-deployment/lib/steps/validate-byob-study-service.js
  addons/addon-base-pre-deployment/packages/base-pre-deployment/package.json
  main/solution/pre-deployment/.eslintrc.json
  main/solution/pre-deployment/.gitignore
  main/solution/pre-deployment/.prettierrc.json
  main/solution/pre-deployment/README.md
  main/solution/pre-deployment/config/build/webpack.config.js
  main/solution/pre-deployment/config/infra/cloudformation.yml
  main/solution/pre-deployment/config/infra/functions.yml
  main/solution/pre-deployment/config/settings/.defaults.yml
  main/solution/pre-deployment/config/settings/.settings.js
  main/solution/pre-deployment/jest.config.js
  main/solution/pre-deployment/jsconfig.json
  main/solution/pre-deployment/package.json
  main/solution/pre-deployment/serverless.yml
  main/solution/pre-deployment/src/lambdas/pre-deployment/handler.js
  main/solution/pre-deployment/src/lambdas/pre-deployment/plugins/plugin-registry.js
  main/solution/pre-deployment/src/lambdas/pre-deployment/plugins/services-plugin.js
  main/solution/pre-deployment/src/lambdas/pre-deployment/plugins/steps-plugin.js
  pnpm-lock.yaml
  scripts/environment-delete.sh
  scripts/environment-deploy.sh
Labels: size/xl

#653 chore: dependency fix
  docs/package.json
  docs/yarn.lock
  scripts/load-test-workspaces/package-lock.json
  scripts/load-test-workspaces/package.json
Labels: size/xl

#655 feat: Allow termination of non-appstream envs
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/plugins/__tests__/aws-account-mgmt-plugin.test.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/plugins/__tests__/env-sc-connection-url-plugin.test.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/plugins/aws-account-mgmt-plugin.js
  addons/addon-base-raas-appstream/packages/base-raas-appstream-services/lib/plugins/env-sc-connection-url-plugin.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/models/environments-sc/ScEnvironment.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/accounts/AccountCard.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/accounts/AccountUtils.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/ScEnvironmentCard.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/ScEnvironmentsList.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentButtons.js
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/onboard-account.cfn.yml
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/__tests__/aws-accounts-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/__tests__/aws-cfn-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/aws-accounts-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/aws-cfn-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-connection-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-service.js
  main/solution/backend/config/infra/cloudformation.yml
  main/solution/backend/src/lambdas/api-handler/plugins/plugin-registry.js
Labels: size/m

#660 fix pre deployment
  main/solution/pre-deployment/config/settings/.settings.js
Labels: size/s

#661 fix: update error message in util function
  addons/addon-base-raas/packages/base-raas-services/lib/helpers/utils.js
Labels: size/xs

#664 doc: adding pre-requisite info for appstream
  scripts/app-stream/README.md
  scripts/app-stream/SETUP.md
Labels: size/xs

#670 fix: lambda error
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/aws-cfn-service.js
Labels: size/s

#669 feat: display Configuration Name and Instance Type on Workspace details card
  addons/addon-base-raas-ui/packages/base-raas-ui/src/models/environments-sc/ScEnvironment.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/ScEnvironmentCard.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/__tests__/ScEnvironmentCard.test.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/setup/SelectConfigurationCards.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/models/environment-types/EnvTypeConfig.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/models/environment-types/__tests__/EnvTypeConfig.test.js
  main/end-to-end-tests/cypress.github.json
  main/end-to-end-tests/cypress.json
  main/end-to-end-tests/cypress.local.example.json
  main/end-to-end-tests/cypress/integration/workspaces.spec.js
Labels: size/m

#680 Feat: Pre-populate variable values in input section of new workspace configuration
  addons/addon-base-ui/packages/base-ui/src/parts/helpers/fields/DropDown.js
  addons/addon-base-ui/packages/base-ui/src/parts/helpers/fields/__tests__/DropDown.test.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/EnvTypeCard.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/EnvTypeEditor.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-config/env-type-config-steps/AccessControlStep.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-config/env-type-config-steps/BaseEnvTypeConfigStep.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-config/env-type-config-steps/BasicInfoStep.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-config/env-type-config-steps/InputParamsStep.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-editor-steps/ConfigStep.js
  main/end-to-end-tests/README.md
  main/end-to-end-tests/cypress.github.json
  main/end-to-end-tests/cypress.json
  main/end-to-end-tests/cypress/integration/workspaces.spec.js
  main/end-to-end-tests/cypress/integration/workspacetypes.spec.js
Labels: size/m

#686 fix: fix the cypress setup for GitHub pipeline (for new EC2 Windows testing capabilities)
  main/end-to-end-tests/cypress.github.json
Labels: size/xs

#685 fix: end2end test terminates existing workspaces from past end-to-end tests
  main/end-to-end-tests/cypress/integration/workspaces.spec.js
Labels: size/xs

#687 fix: opendata for appstream
  main/solution/backend/config/infra/functions.yml
Labels: size/xs

#688 fix: add label to stop e2e tests timing out
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/env-type-editor-steps/ConfigStep.js
  main/end-to-end-tests/cypress/integration/workspacetypes.spec.js
Labels: size/s
