Repository awslabs/service-workbench-on-aws, pull requests merged in 2022-09, with the labels that each got.

#1035 chore: Request package replace
  addons/addon-base-raas-ui/packages/base-raas-ui/package.json
  addons/addon-base-raas/packages/base-raas-services/lib/environment/built-in/environment-url-service.js
  addons/addon-base-raas/packages/base-raas-services/package.json
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/cognito-token-verifier.js
  addons/addon-base-rest-api/packages/services/package.json
  addons/addon-base/packages/services/package.json
  main/integration-tests/package.json
  pnpm-lock.yaml
  scripts/check-dependency-vulnerabilities.sh
Labels: size/xl

#1036 chore: update to latest stable GH runner
  .github/workflows/deploy-integ-appstream-egress.yml
  .github/workflows/deploy-integ.yml
  .github/workflows/mainline-protection.yaml
Labels: size/s

#1037 check if region needs to be set for awscli
  .github/workflows/deploy-integ-appstream-egress.yml
  .github/workflows/deploy-integ.yml
  main/cicd/README.md
  main/cicd/cicd-pipeline/config/buildspec/buildspec-int-tests.yml
  main/integration-tests/README.md
  scripts/run-integration-tests.sh
Labels: size/s

#1039 fix: integration test s3 copy
  scripts/run-integration-tests.sh
Labels: size/xs

#1041 docs: Doc updates change default pw jupyter notebook
  README.md
  docs/Service_Workbench_User_Guide.pdf
  docs/docs/user_guide/sidebar/common/workspaces/accessing_a_workspace.md
Labels: documentation, size/s
