Repository awslabs/service-workbench-on-aws, pull requests merged in 2022-01, with the labels that each got.

#832 fix: force securetransport traffic only for buckets with dynamic bucket policies
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/__tests__/__snapshots__/aws-accounts-service.test.js.snap
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/aws-accounts-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/__tests__/environment-mount-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/environment-mount-service.js
  addons/addon-edit-s3-bucket-policy/README.md
  addons/addon-edit-s3-bucket-policy/packages/edit-s3-bucket-policy/.eslintrc.json
  addons/addon-edit-s3-bucket-policy/packages/edit-s3-bucket-policy/.gitignore
  addons/addon-edit-s3-bucket-policy/packages/edit-s3-bucket-policy/.prettierrc.json
  addons/addon-edit-s3-bucket-policy/packages/edit-s3-bucket-policy/jest.config.js
  addons/addon-edit-s3-bucket-policy/packages/edit-s3-bucket-policy/jsconfig.json
  addons/addon-edit-s3-bucket-policy/packages/edit-s3-bucket-policy/lib/plugins/edit-s3-bucket-policy-plugin.js
  addons/addon-edit-s3-bucket-policy/packages/edit-s3-bucket-policy/lib/steps/__test__/__fixtures__/settings.js
  addons/addon-edit-s3-bucket-policy/packages/edit-s3-bucket-policy/lib/steps/__test__/edit-s3-bucket-policy-service.test.js
  addons/addon-edit-s3-bucket-policy/packages/edit-s3-bucket-policy/lib/steps/edit-s3-bucket-policy-service.js
  addons/addon-edit-s3-bucket-policy/packages/edit-s3-bucket-policy/package.json
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/launch-product/launch-product.js
  main/config/settings/.defaults.yml
  main/solution/backend/config/infra/cloudformation.yml
  main/solution/backend/config/settings/.defaults.yml
  main/solution/post-deployment/config/infra/cloudformation.yml
  main/solution/post-deployment/config/infra/functions.yml
  main/solution/post-deployment/package.json
  main/solution/post-deployment/src/lambdas/post-deployment/plugins/plugin-registry.js
  main/solution/pre-deployment/config/settings/.defaults.yml
  pnpm-lock.yaml
Labels: size/l

#849 fix: use format instead of regex for email validN
  addons/addon-base/packages/services/lib/schema/create-user.json
  addons/addon-base/packages/services/lib/user/__tests__/user-service.test.js
Labels: size/s

#853 chore(release): 4.1.3
  CHANGELOG.md
Labels: size/s

#855 chore: rerun mainline protection check on PR edit
  .github/workflows/mainline-protection.yaml
Labels: size/s

#858 story: enable cognito native user pool
  addons/addon-base-post-deployment/packages/base-post-deployment/lib/steps/__tests__/create-root-user-service.test.js
  addons/addon-base-post-deployment/packages/base-post-deployment/lib/steps/create-root-user-service.js
  addons/addon-base-post-deployment/packages/base-post-deployment/package.json
  addons/addon-base-raas-ui/packages/base-raas-ui/src/models/forms/UserFormUtils.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/users/UpdateUser.js
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/storage-gateway/network-infrastructure.cfn.yml
  addons/addon-base-raas/packages/base-raas-services/lib/schema/create-user.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-user.json
  addons/addon-base-raas/packages/base-raas-services/lib/user/user-authz-service.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/__tests__/provider-service.test.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/__tests__/provisioner-service.test.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/__tests__/user-attributes-mapper-service.test.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provider-service.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provisioner-service.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/user-attributes-mapper-service.js
  addons/addon-base/packages/services/lib/schema/create-user.json
  addons/addon-base/packages/services/lib/schema/update-user.json
  addons/addon-base/packages/services/lib/user/user-service.js
  main/config/settings/.defaults.yml
  main/solution/backend/config/infra/cloudformation.yml
  main/solution/post-deployment/config/infra/cloudformation.yml
  main/solution/post-deployment/config/infra/functions.yml
  main/solution/post-deployment/config/settings/.defaults.yml
  pnpm-lock.yaml
  scripts/get-info.sh
Labels: size/xl

#861 chore: sync feat with develop
  .github/workflows/mainline-protection.yaml
  CHANGELOG.md
  addons/addon-base-post-deployment/packages/base-post-deployment/lib/steps/__tests__/create-root-user-service.test.js
  addons/addon-base-post-deployment/packages/base-post-deployment/lib/steps/create-root-user-service.js
  addons/addon-base-post-deployment/packages/base-post-deployment/package.json
  addons/addon-base-raas-ui/packages/base-raas-ui/src/models/forms/UserFormUtils.js
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/storage-gateway/network-infrastructure.cfn.yml
  addons/addon-base-raas/packages/base-raas-services/lib/schema/create-user.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-user.json
  addons/addon-base-raas/packages/base-raas-services/lib/user/user-authz-service.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/__tests__/provider-service.test.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/__tests__/provisioner-service.test.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/__tests__/user-attributes-mapper-service.test.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provider-service.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provisioner-service.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/user-attributes-mapper-service.js
  addons/addon-base/packages/services/lib/schema/create-user.json
  addons/addon-base/packages/services/lib/schema/update-user.json
  addons/addon-base/packages/services/lib/user/user-service.js
  main/config/settings/.defaults.yml
  main/end-to-end-tests/cypress.github.appstream-egress.json
  main/end-to-end-tests/cypress.github.json
  main/solution/backend/config/infra/cloudformation.yml
  main/solution/post-deployment/config/infra/cloudformation.yml
  main/solution/post-deployment/config/infra/functions.yml
  main/solution/post-deployment/config/settings/.defaults.yml
  pnpm-lock.yaml
  scripts/get-info.sh
  scripts/get-relying-party-info.sh
  scripts/util.sh
Labels: size/xl

#865 fix: root users should be created later
  addons/addon-base-post-deployment/packages/base-post-deployment/lib/plugins/steps-plugin.js
Labels: size/xs

#862 chore(deps): bump follow-redirects to 1.14.7
  scripts/check-commit-status/package-lock.json
  scripts/check-commit-status/package.json
Labels: size/s

#868 fix: provide cognito perms for apihandler
  main/solution/backend/config/infra/cloudformation.yml
Labels: size/xs

#869 chore: Merge develop into feat-internal-auth-dep
  addons/addon-base-post-deployment/packages/base-post-deployment/lib/plugins/steps-plugin.js
  docs/yarn.lock
  main/solution/backend/config/infra/cloudformation.yml
  scripts/check-commit-status/package-lock.json
  scripts/check-commit-status/package.json
Labels: size/s

#870 feat: integ framework update for cognito
  main/integration-tests/config/settings/example.yml
  main/integration-tests/jest.config.js
  main/integration-tests/package.json
  main/integration-tests/support/aws/services.js
  main/integration-tests/support/aws/services/cognito-idp.js
  main/integration-tests/support/complex/delete-user.js
  main/integration-tests/support/resources/users/users.js
  main/integration-tests/support/setup.js
  main/integration-tests/support/utils/generators.js
  main/integration-tests/support/utils/id-token.js
  pnpm-lock.yaml
Labels: size/m

#872 chore: changelog update
  CHANGELOG.md
Labels: size/s

#875 fix: username should be in email format
  addons/addon-base-raas/packages/base-raas-services/lib/schema/create-user.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-user.json
  addons/addon-base/packages/services/lib/schema/create-user.json
  addons/addon-base/packages/services/lib/schema/update-user.json
  addons/addon-base/packages/services/lib/user/__tests__/user-service.test.js
Labels: size/s

#877 fix: temp perm changes for servicecatalog
  main/solution/post-deployment/config/infra/cloudformation.yml
Labels: size/xs

#878 fix: temp cicd for servicecatalog perm change
  main/cicd/cicd-pipeline/config/infra/cloudformation.yml
Labels: size/xs

#880 fix: strengthen CSP header
  addons/addon-base-ui/packages/base-ui/src/parts/Login.js
  addons/addon-base-ui/packages/base-ui/src/parts/MainLayout.js
  main/solution/edge-lambda/config/infra/cloudformation.yml
  main/solution/ui/src/css/basscss-important.css
Labels: size/xl

#857 feat: My study migration
  addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/migration-controller.js
  addons/addon-base-raas/packages/base-raas-rest-api/lib/plugins/routes-plugin.js
  addons/addon-base-raas/packages/base-raas-rest-api/lib/plugins/services-plugin.js
  addons/addon-base-raas/packages/base-raas-services/lib/migration/__tests__/migration-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/migration/migration-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-permission-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/study/helpers/entities/__tests__/study-permissions-methods.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/study/helpers/entities/study-permissions-methods.js
  addons/addon-base-raas/packages/base-raas-services/lib/study/study-permission-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/study/study-service.js
  addons/addon-base/packages/services/lib/user/__tests__/user-service.test.js
  addons/addon-base/packages/services/lib/user/user-service.js
  openapi.yaml
Labels: size/l

#882 chore: bump node-fetch version
  docs/package.json
  docs/yarn.lock
  scripts/check-commit-status/package-lock.json
  scripts/check-commit-status/package.json
Labels: size/m

#885 fix: notify api returns internal error on malformed id
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/data-egress-service.js
Labels: size/xs

#883 feat: enable flow logs for network monitoring
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/onboard-account.cfn.yml
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/__tests__/aws-cfn-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/aws-cfn-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/cfn-templates/cfn-template-service.js
  addons/addon-base-raas/packages/base-raas-workflow-steps/lib/steps/__test__/provision-account.test.js
  addons/addon-base-raas/packages/base-raas-workflow-steps/lib/steps/provision-account/provision-account.js
  main/config/settings/.defaults.yml
  main/solution/backend/config/infra/functions.yml
  main/solution/post-deployment/config/infra/functions.yml
  main/solution/ui/config/environment/env-template.yml
Labels: size/m

#890 Patch release
  CHANGELOG.md
Labels: size/s

#891 chore: version bumps and doc update
  README.md
  addons/addon-base-raas/packages/serverless-packer/README.md
  addons/addon-base-ui/packages/serverless-ui-tools/README.md
  addons/addon-base/packages/serverless-go-build-tools/README.md
  addons/addon-key-pair-mgmt-api/packages/key-pair-mgmt-services/package.json
  docs/docs/deployment/pre_deployment/prereq_commands.md
  docs/docs/installation_guide/installation/cloud9install.md
  docs/package.json
  docs/yarn.lock
  pnpm-lock.yaml
Labels: size/s
