Repository awslabs/service-workbench-on-aws, pull requests merged in 2022-03, with the labels that each got.

#940 fix: no cidr form field in TRE env
  addons/addon-base-raas-ui/packages/base-raas-ui/src/models/forms/CreateInternalEnvForm.js
Labels: size/s

#941 fix: select cidr field only in non-TRE env
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/setup/CreateInternalEnvForm.js
Labels: size/xs

#945 docs: Updates emr not available in tre deployments
  README.md
  docs/Service_Workbench_Post_Deployment_Guide.pdf
  docs/Service_Workbench_User_Guide.pdf
Labels: size/s

#947 fix: OAuth grant type
  addons/addon-base-rest-api/packages/base-controllers/lib/sign-in-controller.js
  addons/addon-base-rest-api/packages/base-controllers/package.json
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/create-cognito-user-pool-schema.json
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provider-service.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provisioner-service.js
  addons/addon-base-ui/packages/base-ui/package.json
  addons/addon-base-ui/packages/base-ui/src/helpers/api.js
  addons/addon-base-ui/packages/base-ui/src/helpers/utils.js
  addons/addon-base-ui/packages/base-ui/src/models/authentication/Authentication.js
  addons/addon-base-ui/packages/base-ui/src/models/authentication/AuthenticationProviderPublicConfig.js
  addons/addon-base-ui/packages/base-ui/src/models/constants/local-storage-keys.js
  pnpm-lock.yaml
Labels: size/m

#950 fix: config integ test
  main/integration-tests/support/resources/authentication/helpers/default-auth-provider-type-cognito.json
Labels: size/xs

#954 chore: release v5.1.0
  CHANGELOG.md
  addons/addon-base-raas/packages/base-raas-services/package.json
  addons/addon-key-pair-mgmt-api/packages/key-pair-mgmt-services/package.json
  docs/package.json
  main/solution/backend/package.json
  pnpm-lock.yaml
  yarn.lock
Labels: size/xl
