Repository awslabs/service-workbench-on-aws, pull requests merged in 2022-05, with the labels that each got.

#984 fix: create log group for flow logs
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/onboard-account.cfn.yml
Labels: size/s

#991 chore: sync feat with develop
  pnpm-lock.yaml
Labels: size/m

#994 chore: new release 5.2.0
  CHANGELOG.md
Labels: size/s

#989 Docs: Adding install new guide
  README.md
  docs/README.md
  docs/Service_Workbench_Install_Guide.pdf
  docs/Service_Workbench_Installation_Guide.pdf
Labels: size/xs

#996 Docs: Relevance labs changes
  docs/Service_Workbench_Install_Guide.pdf
  docs/Service_Workbench_Post_Deployment_Guide.pdf
  docs/Service_Workbench_User_Guide.pdf
Labels: size/xs

#997 chore: release changelog update and bug fix
  CHANGELOG.md
  main/solution/backend/config/infra/functions.yml
Labels: size/s
