Repository awslabs/service-workbench-on-aws, pull requests merged in 2022-02, with the labels that each got.

#895 fix: create aws account exc
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/__tests__/aws-accounts-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/aws-accounts-service.js
Labels: size/s

#897 fix: add attributes for better logging
  addons/addon-base-rest-api/packages/base-controllers/lib/middlewares/prepare-context.js
  addons/addon-base/packages/services/lib/audit/audit-writer-service.js
  addons/addon-base/packages/services/lib/logger/log-transformer.js
  addons/addon-base/packages/services/lib/logger/logger-service.js
  addons/addon-base/packages/services/lib/utils/services-registration-util.js
Labels: size/s

#901 fix: no active internal users
  addons/addon-base/packages/services/lib/user/__tests__/user-service.test.js
  addons/addon-base/packages/services/lib/user/user-service.js
Labels: size/s

#899 fix: user names update
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/__tests__/provider-service.test.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provider-service.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/user-attributes-mapper-service.js
Labels: size/m

#900 chore: Migrate api integ tests
  addons/addon-base-raas/packages/base-raas-services/lib/migration/__tests__/migration-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/migration/migration-service.js
  docs/docs/installation_guide/upgrading/authentication.md
  main/integration-tests/__test__/api-tests/common/migration/my-study-migration.test.js
  main/integration-tests/support/resources.js
  main/integration-tests/support/resources/migration/migration.js
  openapi.yaml
Labels: size/m

#904 fix: better internal auth error messages
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/authentication-provider-config-service.js
  addons/addon-base/packages/services/lib/user/__tests__/user-service.test.js
  addons/addon-base/packages/services/lib/user/user-service.js
Labels: size/s

#902 chore: sync with develop
  CHANGELOG.md
  README.md
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/onboard-account.cfn.yml
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/__tests__/aws-accounts-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/__tests__/aws-cfn-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/aws-accounts-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/aws-accounts/aws-cfn-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/cfn-templates/cfn-template-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/data-egress/data-egress-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/user/__tests__/user-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/user/user-service.js
  addons/addon-base-raas/packages/base-raas-workflow-steps/lib/steps/__test__/provision-account.test.js
  addons/addon-base-raas/packages/base-raas-workflow-steps/lib/steps/provision-account/provision-account.js
  addons/addon-base-raas/packages/serverless-packer/README.md
  addons/addon-base-rest-api/packages/base-controllers/lib/middlewares/prepare-context.js
  addons/addon-base-ui/packages/serverless-ui-tools/README.md
  addons/addon-base/packages/serverless-go-build-tools/README.md
  addons/addon-base/packages/services/lib/audit/audit-writer-service.js
  addons/addon-base/packages/services/lib/logger/log-transformer.js
  addons/addon-base/packages/services/lib/logger/logger-service.js
  addons/addon-base/packages/services/lib/utils/services-registration-util.js
  addons/addon-key-pair-mgmt-api/packages/key-pair-mgmt-services/package.json
  docs/docs/deployment/post_deployment/appstream.md
  docs/docs/deployment/pre_deployment/prereq_commands.md
  docs/docs/installation_guide/installation/cloud9install.md
  docs/package.json
  docs/yarn.lock
  main/config/settings/.defaults.yml
  main/solution/backend/config/infra/functions.yml
  main/solution/post-deployment/config/infra/functions.yml
  main/solution/ui/config/environment/env-template.yml
  pnpm-lock.yaml
Labels: size/xl

#909 fix: reorder pre dep checks
  addons/addon-internal-auth-dep-check/packages/internal-auth-dep-check/lib/steps/internal-auth-dep-check-service.js
Labels: size/xs

#910 fix: create non-internal users in integ tests
  addons/addon-base-rest-api/packages/base-controllers/lib/sign-in-controller.js
  main/integration-tests/__test__/api-tests/common/authentication/create-auth-id-token.test.js
  main/integration-tests/__test__/api-tests/common/public-auth-provider/public-auth-provider-api.test.js
  main/integration-tests/__test__/api-tests/common/users/update-user-password.test.js
  main/integration-tests/support/complex/delete-user.js
  main/integration-tests/support/resources/authentication/authentication-id-token.js
  main/integration-tests/support/resources/authentication/authentication-id-tokens.js
  main/integration-tests/support/resources/authentication/authentication.js
  main/integration-tests/support/resources/users/users.js
  main/integration-tests/support/setup.js
  openapi.yaml
Labels: size/m

#912 chore: sync with upstream
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/__tests__/provider-service.test.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provider-service.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/user-attributes-mapper-service.js
  pnpm-lock.yaml
Labels: size/xl

#915 fix: integ tests for auth change
  main/integration-tests/__test__/api-tests/common/authentication/get-auth-provider-configs.test.js
  main/integration-tests/__test__/api-tests/common/user/get-user.test.js
  main/integration-tests/__test__/api-tests/common/user/update-user.test.js
  main/integration-tests/__test__/api-tests/common/users/update-user.test.js
  main/integration-tests/support/resources/authentication/authentication-provider-configs.js
  main/integration-tests/support/resources/authentication/authentication-provider-types.js
Labels: size/s

#918 fix: pre-deployment checks work with fresh deployment
  addons/addon-base/packages/services/lib/__mocks__/db-service.js
  addons/addon-internal-auth-dep-check/packages/internal-auth-dep-check/lib/steps/__test__/internal-auth-dep-check-service.test.js
  addons/addon-internal-auth-dep-check/packages/internal-auth-dep-check/lib/steps/internal-auth-dep-check-service.js
  main/solution/pre-deployment/config/infra/cloudformation.yml
Labels: size/s

#919 chore(release): 5.0.0
  CHANGELOG.md
Labels: size/s

#925 chore: dependency updates
  main/end-to-end-tests/package-lock.json
  main/end-to-end-tests/package.json
  pnpm-lock.yaml
  scripts/load-test-workspaces/package.json
Labels: size/xl

#930 fix: -raas-master-artifacts versioning
  main/solution/prepare-master-acc/serverless.yml
Labels: size/xs

#928 fix: email TLD can be longer than 3 chars
  addons/addon-base-raas/packages/base-raas-services/lib/schema/create-user.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-user.json
  addons/addon-base/packages/services/lib/schema/create-user.json
  addons/addon-base/packages/services/lib/schema/update-user.json
  addons/addon-base/packages/services/lib/user/__tests__/user-service.test.js
  main/solution/post-deployment/config/infra/cloudformation.yml
Labels: size/s

#931 fix: verbose errors
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/terminate-product/terminate-product.js
Labels: size/s

#935 fix: wide cidr warning and env config dep
  addons/addon-base-raas-ui/packages/base-raas-ui/src/models/forms/CreateInternalEnvForm.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/setup/CreateInternalEnvForm.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/setup/SelectConfigurationCards.js
Labels: size/s
