Repository awslabs/service-workbench-on-aws, pull requests merged in 2022-10, with the labels that each got.

#1048 fix: sls default profile fix
  addons/addon-base/packages/serverless-settings-helper/README.md
  addons/addon-base/packages/serverless-settings-helper/examples/basic/serverless.yml
  main/cicd/cicd-pipeline/serverless.yml
  main/cicd/cicd-source/serverless.yml
  main/solution/backend/serverless.yml
  main/solution/edge-lambda/serverless.yml
  main/solution/environment-tools/serverless.yml
  main/solution/infrastructure/serverless.yml
  main/solution/machine-images/serverless.yml
  main/solution/post-deployment/serverless.yml
  main/solution/pre-deployment/serverless.yml
  main/solution/prepare-master-acc/serverless.yml
  main/solution/ui/serverless.yml
Labels: size/s

#1049 fix: add aws config to workflow
  .github/workflows/deploy-integ.yml
Labels: size/xs

#1052 fix: buildspec use yum
  main/cicd/cicd-pipeline/config/buildspec/buildspec.yml
Labels: size/xs

#1050 fix: use "" as default profile if no awsProfile
  .github/workflows/deploy-integ-appstream-egress.yml
  .github/workflows/deploy-integ.yml
  addons/addon-base/packages/serverless-settings-helper/README.md
  addons/addon-base/packages/serverless-settings-helper/examples/basic/serverless.yml
  main/cicd/cicd-pipeline/config/buildspec/buildspec-uninstall.yml
  main/cicd/cicd-pipeline/config/buildspec/buildspec.yml
  main/cicd/cicd-pipeline/serverless.yml
  main/cicd/cicd-source/serverless.yml
  main/solution/backend/serverless.yml
  main/solution/edge-lambda/serverless.yml
  main/solution/environment-tools/serverless.yml
  main/solution/infrastructure/serverless.yml
  main/solution/machine-images/serverless.yml
  main/solution/post-deployment/serverless.yml
  main/solution/pre-deployment/serverless.yml
  main/solution/prepare-master-acc/serverless.yml
  main/solution/ui/serverless.yml
Labels: size/s

#1053 fix: cicd pipeline permissions
  main/cicd/cicd-pipeline/config/infra/cloudformation.yml
  main/cicd/cicd-pipeline/serverless.yml
Labels: size/s

#1054 fix: tre egress store data updated S3 return
  main/integration-tests/__test__/api-tests/appstream-egress-enabled/data-egress/get-data-egress.test.js
Labels: size/xs

#1055 chore(release): 5.2.3
  CHANGELOG.md
Labels: size/s

#1057 feat: Add integration tests for users and user-roles controllers
  main/integration-tests/__test__/api-tests/common/user-roles/get-user-roles.test.js
  main/integration-tests/__test__/api-tests/common/users/bulk-add-users.test.js
  main/integration-tests/__test__/api-tests/common/users/create-user.test.js
  main/integration-tests/__test__/api-tests/common/users/get-users.test.js
  main/integration-tests/__test__/api-tests/common/users/update-user.test.js
Labels: size/m

#1058 fix: minimatch alert
  docs/package.json
  docs/yarn.lock
  main/end-to-end-tests/package-lock.json
  main/end-to-end-tests/package.json
  scripts/app-stream/package-lock.json
  scripts/app-stream/package.json
  scripts/load-test-workspaces/package-lock.json
  scripts/load-test-workspaces/package.json
Labels: size/xl

#1061 chore: update env-delete script
  main/cicd/README.md
  main/cicd/cicd-pipeline/config/infra/cloudformation.yml
  scripts/environment-delete.sh
Labels: size/m
