Repository awslabs/service-workbench-on-aws, pull requests merged in 2022-04, with the labels that each got.

#966 chore: 5.1.1release
  CHANGELOG.md
Labels: size/m

#970 fix: first install
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provisioner-service.js
Labels: size/s

#976 chore: vulnerable dependency version fix
  docs/package.json
  docs/yarn.lock
  pnpm-lock.yaml
Labels: size/xl

#978 chore: vulnerable dependency version fix (#976)
  docs/package.json
  docs/yarn.lock
  pnpm-lock.yaml
Labels: size/xl
