Repository awslabs/service-workbench-on-aws, pull requests merged in 2022-12, with the labels that each got.

#1075 fix: fix input validation and escape html on popups
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/files/FileDropZone.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/files/FileUpload.js
  addons/addon-base-ui/packages/base-ui/src/helpers/notification.js
  addons/addon-key-pair-mgmt-api/packages/key-pair-mgmt-services/lib/key-pair/__tests__/key-pair-service.test.js
  addons/addon-key-pair-mgmt-api/packages/key-pair-mgmt-services/lib/key-pair/key-pair-service.js
  addons/addon-key-pair-mgmt-api/packages/key-pair-mgmt-services/lib/key-pair/schema/create-key-pair.js
  addons/addon-key-pair-mgmt-api/packages/key-pair-mgmt-services/lib/key-pair/schema/update-key-pair.js
  openapi.yaml
Labels: size/m

#1078 chore(release): 5.2.4
  CHANGELOG.md
Labels: size/s

#1079 fix: Sagemaker compatability fix with AL2
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/sagemaker-notebook-instance.cfn.yml
  main/solution/post-deployment/config/environment-files/bin/mount_s3.sh
  main/solution/post-deployment/config/environment-files/bootstrap.sh
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/boto3/python2-boto3-1.4.4-1.amzn2.noarch.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/basesystem-10.0-7.amzn2.0.1.noarch.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/bash-4.2.46-34.amzn2.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/filesystem-3.2-25.amzn2.0.4.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/fuse-2.9.2-11.amzn2.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/glibc-2.26-58.amzn2.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/glibc-common-2.26-58.amzn2.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/info-5.1-5.amzn2.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/libgcc-7.3.1-14.amzn2.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/libselinux-2.5-12.amzn2.0.2.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/libsepol-2.5-8.1.amzn2.0.2.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/ncurses-base-6.0-8.20170212.amzn2.1.3.noarch.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/ncurses-compat-libs-6.0-8.20170212.amzn2.1.3.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/ncurses-libs-6.0-8.20170212.amzn2.1.3.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/nspr-4.32.0-1.amzn2.0.1.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/nss-softokn-freebl-3.67.0-3.amzn2.0.1.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/nss-util-3.67.0-1.amzn2.0.1.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/setup-2.8.71-10.amzn2.0.1.noarch.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/tzdata-2022a-1.amzn2.noarch.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/which-2.20-7.amzn2.0.2.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/zlib-1.2.7-17.amzn2.0.2.x86_64.rpm
  main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/fuse-2.9.4_AL2/zlib-1.2.7-19.amzn2.0.1.x86_64.rpm
Labels: size/s

#1074 fix: add permissions for stgEnvname and stgNamespace to IAM roles
  main/cicd/cicd-pipeline/config/infra/cloudformation.yml
  main/cicd/cicd-pipeline/config/settings/.defaults.yml
  package-lock.json
Labels: size/xl

#1085 fix: UI properly sorts Projects with Detail button
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/projects/ProjectConfigure.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/projects/ProjectsList.js
  main/end-to-end-tests/README.md
  main/end-to-end-tests/cypress/integration/common/projects.spec.js
Labels: size/m

#1087 fix: projects test was using the wrong role
  main/end-to-end-tests/cypress/integration/common/projects.spec.js
Labels: size/xs

#1082 chore: update bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: size/xs

#1088 chore(release): 5.2.6
  CHANGELOG.md
Labels: size/s
