Repository awslabs/service-workbench-on-aws, pull requests merged in 2023-03, with the labels that each got.

#1139 add git actions to deploy to rstudio env
  .github/workflows/deploy-integ.yml
  main/end-to-end-tests/RStudioGithubConfig.yml
  scripts/read-values-for-github-action-rstudio.sh
Labels: size/s

#1140 Revert "chore(deps): bump golang.org/x/sys (#1138)"
  addons/addon-raas-s3-copy/packages/s3-synchronizer/go.mod
  addons/addon-raas-s3-copy/packages/s3-synchronizer/go.sum
Labels: size/s

#1149 fix: integ test pipeline script
  scripts/run-integration-tests.sh
Labels: size/xs

#1150 docs: remove Docusaurus and use IG
  .gitignore
  CHANGELOG.md
  README.md
  docs/README.md
  docs/Service_Workbench_Install_Guide.pdf
  docs/docs/configuration_guide/activedirectory.md
  docs/docs/configuration_guide/auth0.md
  docs/docs/configuration_guide/workflow.md
  docs/docs/deployment/configuration/auth/configuring_auth0.md
  docs/docs/deployment/configuration/auth/enabling_ad.md
  docs/docs/deployment/deployment/index.md
  docs/docs/deployment/post_deployment/appstream.md
  docs/docs/deployment/post_deployment/aws_accounts.md
  docs/docs/deployment/post_deployment/create_admin_user.md
  docs/docs/deployment/post_deployment/create_index_project.md
  docs/docs/deployment/post_deployment/import_service_catalog_products.md
  docs/docs/deployment/post_deployment/link_aws_account.md
  docs/docs/deployment/reference/aws_services.md
  docs/docs/deployment/reference/egress_store_approval_process.md
  docs/docs/deployment/reference/iam_role.md
  docs/docs/deployment/reference/prepare_master_account.md
  docs/docs/installation_guide/architecture.md
  docs/docs/installation_guide/installation/ami-install.md
  docs/docs/installation_guide/installation/pre-installation/documentation.md
  docs/docs/installation_guide/installation/pre-installation/instance-req.md
  docs/docs/installation_guide/installation/pre-installation/tool-req.md
  docs/docs/installation_guide/upgrading/authentication.md
  docs/docs/user_guide/introduction.md
  docs/docusaurus.config.js
  docs/package.json
  docs/service-workbench-on-aws-implementation-guide.pdf
  docs/sidebars.js
  docs/src/css/custom.css
  docs/src/css/custom.original.css
  docs/src/pages/index.js
  docs/src/pages/original.css
  docs/src/pages/styles.module.css
  docs/static/img/undraw_docusaurus_mountain.svg
  docs/static/img/undraw_docusaurus_react.svg
  docs/static/img/undraw_docusaurus_tree.svg
  docs/yarn.lock
Labels: size/xl

#1153 fix: sagemaker autostop
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/sagemaker-notebook-instance.cfn.yml
Labels: size/xs

#1154 fix: autostop sagemaker fix for non TRE/no study mounting
  main/end-to-end-tests/cypress.github.json
  main/solution/post-deployment/config/environment-files/bootstrap.sh
Labels: size/xs

#1164 Add elasticmapreduce:AddTags permission to LaunchConstraint role
  main/solution/post-deployment/config/infra/cloudformation.yml
Labels: size/xs
